name: Mirror WordFence

# Controls when the workflow will run
on:
  schedule:
    - cron: "30 0 * * *" # Run this sync once per day.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mirror:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          
      - name: Install git-svn
        run: |
          sudo add-apt-repository ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install git-svn
          
      - name: Checkout Wordfence from WordPress SVN repo
        run: svn co https://plugins.svn.wordpress.org/wordfence/ wordfence-svn
      
      - name: Generate users.txt file
        run: |
          cd wordfence-svn
          svn log -q | awk -F '|' '/^r/ {gsub(/ /, "", $2); sub(" $", "", $2); print $2" = "$2" <"$2">"}' | sort -u > ../users.txt
          cd ..
          
      - name: Create Git clone of SVN repository
        run: git svn clone --no-minimize-url --stdlayout -r433177:HEAD --authors-file=users.txt https://plugins.svn.wordpress.org/wordfence/ wordfence-git
        
      - name: Push clone to Github
        env: 
          GH_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
        run: |
          cd wordfence-git
          git remote add github https://anubisthejackle:$GH_DEPLOY_KEY@github.com/wp-plugins-mirror/wordfence.git
          git push --force --all --repo github
